apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-affinity
  labels:
    app: nginx-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
