FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app.py /app/
RUN pip3 install flask
EXPOSE 5000
CMD ["python3", "app.py"]
