apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer        # exposes externally
  ports:
    - protocol: TCP
      port: 80              # external port
      targetPort: 80 