FROM --platform=amd64 python:3.11-slim

WORKDIR /app
EXPOSE 5000
COPY requirements.txt requirements.txt
COPY main.py main.py

RUN pip install --no-cache-dir -r requirements.txt

RUN useradd -m appuser
RUN chown -R appuser:appuser /app
USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]